# Generated by Django 2.2.5 on 2020-10-04 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('Roleid', models.AutoField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field_name', models.CharField(help_text='Enter field documentation', max_length=20)),
                ('username', models.CharField(help_text='Nick Name', max_length=50)),
                ('email', models.CharField(help_text='correo@dom.com', max_length=100)),
                ('password', models.CharField(help_text='********', max_length=50)),
                ('first_name', models.CharField(help_text='NICOLAS', max_length=200)),
                ('last_name', models.CharField(help_text='ARRIETA', max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Role')),
            ],
        ),
    ]
